### ISSUE TITLE
asc signature file

### ISSUE THREAD

**Issue by LinuxUser255** [jython/jython.github.io#23]
Hello,
Regarding the OpenPGP Pbublic Keys at  https://www.jython.org/download

I am able to acquire a signing key:
gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 875C3EF9DC4638E3
That worked fine.

However, I cannot find an asc signature file to go with the Jython Standalone.
I've checked both the Jython and jython.github.io repos and couldn't find it.

Is your .asc hosted somewhere else?

**Comment by jeff5** [comment]
It's next to the jar where we host it on Sonatype.

One of the links on our download page takes you to the [page at Sonatype](https://search.maven.org/artifact/org.python/jython-standalone/2.7.2/jar), then "Browse" (folder icon) takes you to the raw directory of [uploaded files](https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/).

Does this give you what's needed?

**Comment by LinuxUser255** [comment]
Yes sir! Exactly what I needed.
Thank you!
